from django.db import models

class existanceType(models.IntegerChoices):
    """Describes how the edition exists on this server"""
    LOCAL = 0 # Basic local files
    UNGENERATED = 1 # It should be generated from another file.
    GENERATING = 2 # It is currently being generated.
    AUTOGENERATED = 3 # It is auto generated on our server from a different file.
    REMOTE = 4 # It exists on a remote server, but isnt mirrored. Just links to the remote file. (saves storage)
    MIRROREDREMOTE = 5 # It exists on a remote server, and is copied locally by this instance for reliability/speed/archival purposes.

