# Generated by Django 5.0.3 on 2024-03-13 21:33

import django.db.models.deletion
from django.db import migrations, models

#See migration 1

class Migration(migrations.Migration):

    dependencies = [
        ('archive_backend', '0002_remote_peer_self_creation'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='remotepeer',
            name='from_remote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_backend.remotepeer'),
        ),
    ]
