# Generated by Django 5.0.3 on 2024-03-13 21:04

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePeer',
            fields=[
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=200)),
                ('site_adress', models.CharField(max_length=500)),
                ('mirror_files', models.BooleanField(blank=True, default=False)),
                ('peers_of_peer', models.BooleanField(blank=True, default=True)),
                ('last_checkin', models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('is_this_site', models.BooleanField(blank=True, default=False)),
                ('from_remote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArchiveBackend.remotepeer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
