# Generated by Django 5.0.3 on 2024-03-13 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArchiveBackend', '0002_RemotePeerSelfCreation'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='remotepeer',
            name='from_remote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArchiveBackend.remotepeer'),
        ),
    ]
